### ISSUE TITLE
Investigate `SEVERE UNKNOWN GATEWAY EVENT` after login

### ISSUE THREAD

**Issue by V3ntus** [V3ntus/nyxx-self#1]
Does not interfere with normal operation, seems like.
```
[2023-03-17 18:38:15.252259] [INFO] [Connection Manager] Connected and ready! Logged as `...`
[2023-03-17 18:38:15.252746] [FINE] [Shard 0] Handling received message from runner
[2023-03-17 18:38:15.253303] [FINER] [Shard 0] Sequence: -3
Data: {t: SESSIONS_REPLACE, s: 2, op: 0, d: [{status: dnd, session_id: ..., client_info: {version: 0, os: other, client: web}, activities: []}]}
[2023-03-17 18:38:15.255074] [SEVERE] [Shard 0] UNKNOWN GATEWAY EVENT: {t: SESSIONS_REPLACE, s: 2, op: 0, d: [{status: dnd, session_id: ..., client_info: {version: 0, os: other, client: web}, activities: []}]}
Error: autogenerated stack trace for SEVERE UNKNOWN GATEWAY EVENT: {t: SESSIONS_REPLACE, s: 2, op: 0, d: [{status: dnd, session_id: ..., client_info: {version: 0, os: other, client: web}, activities: []}]}
Stack trace:
#0      Logger.log (package:logging/src/logger.dart:200:33)
#1      Logger.severe (package:logging/src/logger.dart:269:7)
#2      Shard.dispatch (package:nyxx/src/internal/shard/shard.dart:687:18)
#3      Shard.handlePayload (package:nyxx/src/internal/shard/shard.dart:327:9)
#4      Shard.handle (package:nyxx/src/internal/shard/shard.dart:239:16)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#6      CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#11     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#12     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#17     _StreamController._add (dart:async/stream_controller.dart:648:7)
#18     _StreamController.add (dart:async/stream_controller.dart:596:5)
#19     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

**Comment by V3ntus** [comment]
> Undocumented event that can safely be ignored.  

https://github.com/Rapptz/discord.py/issues/1851#issuecomment-457880626
